baseurl = "/"
relativeURLs = true
languageCode = "de-de"
title = "greenWeb"
theme = "hugo-lithium-theme-master"
googleAnalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm", "section", "404"]

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"
    

[[menu.main]]
    name = "About the project"
    url = "/about/"
[[menu.main]]
    name = "Impressum"
    url = "/impressum/"
[[menu.main]]
    name = "Key findings"
    url = "/key findings/"


[params]
    mainSections = ["post"]

    description = ""

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

    [params.icon]
    url = "favicon.ico"

